name:                yesod-dhall
version:             0.1.0.0
github:              "plow-technologies/yesod-dhall"
license:             BSD3
author:              "Edward Amsden"
maintainer:          "edward.amsden@plowtech.net"
copyright:           "2018 Plow Technologies"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/plow-technologies/yesod-dhall#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- dhall
- http-types
- prettyprinter
- text
- wai
- yesod
- yesod-core

library:
  source-dirs: src

tests:
  yesod-dhall-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yesod-dhall
